### ISSUE TITLE
Multiple options with the same name under one host

### ISSUE THREAD

**Issue by kradalby** [9seconds/concierge#4]
Hi

Currently, if I would like to have multiple options with the same name, for example, multiple LocalForward under one hostname, only the last listed will be present in the transpiled .ssh/config.

I believe this is due to the fact that host options are stored in a dictionary (or a Data object), and that the last given option of the name will prevail.

Example:

.conciergerc
```
Host brumm
    HostName tussi
    Port 22
    User root
    LocalForward 80 brumm:80
    LocalForward 443 brumm:443
    LocalForward 902 brumm:902
    LocalForward 903 brumm:903
```

.ssh/config
```
Host brumm
    HostName tussi
    LocalForward 903 brumm:903
    Port 22
    User root
```

I am not what is the best/easiest way to fix/implement this, but I guess it is worth to point out.

**Comment by 9seconds** [comment]
Oh, you absolutely correct. Bug, bug!
