### ISSUE TITLE
Error with pbr during packaging

### ISSUE THREAD

**Issue by milouse** [9seconds/concierge#9]
Hi!

I try to package your work for Archlinux. It seems I install all the needed dependancies:

* inotify_simple
* setuptools
* pbr

But when I try to do a simple `python setup.py install --root=../pkg/concierge/` (classic way to create arch packages as this operation occurs in a chroot) I got the following error:

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.5/site-packages/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.5/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.5/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.5/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3.5/site-packages/pbr/packaging.py", line 725, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /home/etienne/Applis/divers/pkgbuilds/concierge/concierge-0.2/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure
that git is installed?
```

Even if I try to call setup.py directly as my current user (with git available in path) I keep getting this error. I also try to tweak `setup.cfg` to remove what seems to be useless in my case (pgi or tox ref...) but I didn't got more success.

Any idea how to fix this? Or could you provide just a simple setup.py file without having to deal with pbr?

Thank you very much.

**Comment by 9seconds** [comment]
Oh, pbr again :( I will rewrite setup.py to get rid of it. It brings more problems than solves apparently :/

**Comment by milouse** [comment]
Enjoy: https://aur.archlinux.org/packages/concierge/ :)
